name: section8
description: Shop App for state management

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^1.0.0
  provider: ^4.0.5+1
  intl: ^0.16.1
  http: ^0.12.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: asset/fonts/Lato-Regular.ttf
        - asset: asset/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: asset/fonts/Anton-Regular.ttf


